// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApprovalPendingPayload = { call_id: string, tool_name: string, tool_target: string | null, preview: string, tool_label: string, is_diff: boolean, };

export type ConfigLoadedPayload = { toml: string, };

export type ConfigSavedPayload = { message: string, };

export type DataDirPayload = { path: string, };

export type DisplayEntry = { "type": "chat", role: DisplayRole, content: string, thinking: string | null, } | { "type": "tool", call_id: string, name: string, args_display: string, result: string | null, diff_preview: string | null, };

export type DisplayRole = "user" | "assistant" | "system";

export type ErrorPayload = { message: string, };

export type FatigueUpdatePayload = { fatigue: number, turns: number, tool_calls: number, desc: string, };

export type InitPayload = { entries: Array<DisplayEntry>, current_usage: UsageMetrics | null, model_name: string, };

/**
 * A single session's aggregated usage (one awake or sleep cycle).
 */
export type SessionUsage = { scope: UsageScope, start_time: string, prompt_tokens: number, completion_tokens: number, total_tokens: number, reasoning_tokens: number, cache_hit_tokens: number, cache_miss_tokens: number, iterations: number, };

export type TextDeltaPayload = { delta: string, };

export type TextDonePayload = { full_text: string, };

export type ThinkingDeltaPayload = { delta: string, };

export type ToolCallingPayload = { call_id: string, name: string, display: string, };

export type ToolRejectedPayload = { call_id: string, feedback: string, };

export type ToolResultPayload = { call_id: string, name: string, result: string, diff_preview: string | null, };

export type UsageMetrics = { prompt_tokens: number, completion_tokens: number, total_tokens: number, reasoning_tokens: number, cache_hit_tokens: number, cache_miss_tokens: number, };

export type UsageScope = "awake" | "sleep";

export type UsageStatsLoadedPayload = { sessions: Array<SessionUsage>, };

export type UsageUpdatePayload = { metrics: UsageMetrics, };

export type WakingUpPayload = { dream: string, };

/**
 * ── Module-scope anchor for TS export (don't call `export_all` on payload types) ──
 */
export type _AllPayloads = { init: InitPayload, thinking_delta: ThinkingDeltaPayload, text_delta: TextDeltaPayload, text_done: TextDonePayload, tool_calling: ToolCallingPayload, tool_result: ToolResultPayload, approval_pending: ApprovalPendingPayload, tool_rejected: ToolRejectedPayload, error: ErrorPayload, fatigue_update: FatigueUpdatePayload, usage_update: UsageUpdatePayload, usage_stats_loaded: UsageStatsLoadedPayload, waking_up: WakingUpPayload, config_loaded: ConfigLoadedPayload, config_saved: ConfigSavedPayload, data_dir: DataDirPayload, };
